name: Contexts
on: push
jobs: 
    print: 
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.actor}}"
            - run: echo "${{ github.repository }}"
            - run: echo "${{ runner.name }}"
            - run: echo "${{ runner.os }}"
            - run: echo "${{ runner.arch }}"
            - run: echo "${{ runner.tool_cache }}"
 
